version: '3.9'

# MapS: TheIsland, ScorchedEarth_P, Aberration_P, Extinction, Genesis, TheCenter, Ragnarok, CrystalIsles, Valguero_P, Fjordur, Gen2, LostIsland
# Events: Easter, Arkaeology, ExtinctionChronicles, WinterWonderland, vday, Summer, FearEvolved, TurkeyTrial, birthday, None

services:
  island:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/redactdigital/docker-ark-survival:latest
    volumes:
      # This is where the ARK saved game data is stored, and also where
      # the ARK server configuration file is stored.
      - ./ark-server:/home/ark/server/serverfiles
    ports:
      # The connection port for the ARK game client
      - 7777:7777/udp
      # Raw UDP port (should always be game client port + 1)
      - 7778:7778/udp
      # Query port used to list servers on the internet
      - 27015:27015/udp
      # RCON management port
      - 27020:27020/tcp
    environment:
      MAP: TheIsland
      CLUSTER: redactcluster
      EVENT: None
      OPTIONS: '-automanagedmods -NoTransferFromFiltering -ForceAllowCaveFlyers -usecache -NoBattleEye -crossplay -culture=en'
      # MULTIHOME: 10.1.1.1

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.service == ark-server
