version: '3.9'

services:
  island:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/redactdigital/docker-ark-survival:latest
    volumes:
      # This is where the ARK saved game data is stored, and also where
      # the ARK server configuration file is stored.
      - ./ark-server:/home/ark/server/serverfiles
    ports:
      # The connection port for the ARK game client
      - 7777:7777/udp
      # Raw UDP port (should always be game client port + 1)
      - 7778:7778/udp
      # Query port used to list servers on steam (Query Port cannot be between 27020 and 27050 due to Steam using those ports)
      - 27015:27015/udp
      # RCON management port
      - 27020:27020/tcp
    environment:
      MAP: TheIsland
      CLUSTER: redactcluster
      EVENT: Summer
      OPTIONS: '-NoTransferFromFiltering -ForceAllowCaveFlyers -usecache -NoBattlEye -crossplay -culture=en -EnableIdlePlayerKick -ServerRCONOutputTribeLogs -gameplaylogging'
      CUSTOM_PARAMS: '?OverrideOfficialDifficulty=5.0?AllowCrateSpawnsOnTopOfStructures=true?AllowFlyingStaminaRecovery?ShowFloatingDamageText=true'

  fjordur:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/redactdigital/docker-ark-survival:latest
    volumes:
      # This is where the ARK saved game data is stored, and also where
      # the ARK server configuration file is stored.
      - ./ark-server:/home/ark/server/serverfiles
    ports:
      # The connection port for the ARK game client
      - 7779:7779/udp
      # Raw UDP port (should always be game client port + 1)
      - 7780:7780/udp
      # Query port used to list servers on steam (Query Port cannot be between 27020 and 27050 due to Steam using those ports)
      - 27017:27017/udp
      # RCON management port
      - 27022:27022/tcp
    environment:
      MAP: Fjordur
      CLUSTER: redactcluster
      EVENT: Summer
      OPTIONS: '-NoTransferFromFiltering -ForceAllowCaveFlyers -usecache -NoBattlEye -crossplay -culture=en -EnableIdlePlayerKick -ServerRCONOutputTribeLogs -gameplaylogging'
      CUSTOM_PARAMS: '?OverrideOfficialDifficulty=5.0?AllowCrateSpawnsOnTopOfStructures=true?AllowFlyingStaminaRecovery?ShowFloatingDamageText=true'
      PORT: 7779
      QUERY_PORT: 27017
      RCON_PORT: 27022

  ragnarok:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/redactdigital/docker-ark-survival:latest
    volumes:
      # This is where the ARK saved game data is stored, and also where
      # the ARK server configuration file is stored.
      - ./ark-server:/home/ark/server/serverfiles
    ports:
      # The connection port for the ARK game client
      - 7781:7781/udp
      # Raw UDP port (should always be game client port + 1)
      - 7782:7778/udp
      # Query port used to list servers on steam (Query Port cannot be between 27020 and 27050 due to Steam using those ports)
      - 27019:27019/udp
      # RCON management port
      - 27024:27024/tcp
    environment:
      MAP: Ragnarok
      CLUSTER: redactcluster
      EVENT: Summer
      OPTIONS: '-NoTransferFromFiltering -ForceAllowCaveFlyers -usecache -NoBattlEye -crossplay -culture=en -EnableIdlePlayerKick -ServerRCONOutputTribeLogs -gameplaylogging'
      CUSTOM_PARAMS: '?OverrideOfficialDifficulty=5.0?AllowCrateSpawnsOnTopOfStructures=true?AllowFlyingStaminaRecovery?ShowFloatingDamageText=true'
      PORT: 7781
      QUERY_PORT: 27019
      RCON_PORT: 27024

  genesis-2:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/redactdigital/docker-ark-survival:latest
    volumes:
      # This is where the ARK saved game data is stored, and also where
      # the ARK server configuration file is stored.
      - ./ark-server:/home/ark/server/serverfiles
    ports:
      # The connection port for the ARK game client
      - 7783:7783/udp
      # Raw UDP port (should always be game client port + 1)
      - 7784:7778/udp
      # Query port used to list servers on steam (Query Port cannot be between 27020 and 27050 due to Steam using those ports)
      - 27021:27021/udp
      # RCON management port
      - 27026:27026/tcp
    environment:
      MAP: Gen2
      CLUSTER: redactcluster
      EVENT: Summer
      OPTIONS: '-NoTransferFromFiltering -ForceAllowCaveFlyers -usecache -NoBattlEye -crossplay -culture=en -EnableIdlePlayerKick -ServerRCONOutputTribeLogs -gameplaylogging'
      CUSTOM_PARAMS: '?OverrideOfficialDifficulty=5.0?AllowCrateSpawnsOnTopOfStructures=true?AllowFlyingStaminaRecovery?ShowFloatingDamageText=true'
      PORT: 7783
      QUERY_PORT: 27021
      RCON_PORT: 27026

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.service == ark-server
