version: '3.9'

# MapS: TheIsland, ScorchedEarth_P, Aberration_P, Extinction, Genesis, TheCenter, Ragnarok, CrystalIsles, Valguero_P, Fjordur, Gen2, LostIsland
# Events: Easter, Arkaeology, ExtinctionChronicles, WinterWonderland, vday, Summer, FearEvolved, TurkeyTrial, birthday, None

services:
  island:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/redactdigital/docker-ark-survival:latest
    volumes:
      # The ARK server config files. These are the files you would normally edit to change the server settings.
      # This is why we mount them to the host so that they can be edited outside of the container.
      # - ./ark-server/config:/home/ark/server/serverfiles/ShooterGame/Saved/Config/LinuxServer

      # The ARK server backup files. These are backups of the server data files. These should be mounted to the host
      # so that they can be backed up to a remote location.
      # - ./ark-server/backups:/home/ark/server/serverfiles/ShooterGame/Saved/SavedArks

      # The ARK server data files. These are the files that are generated by the server, such as the saved game data,
      # and the player profiles. These files are not editable, so we don't need to mount them to the host.
      # However, feel free to mount them if you want.
      - ark-server:/home/ark/server/serverfiles
    ports:
      # The connection port for the ARK game client
      - 7777:7777/udp
      # Raw UDP port (should always be game client port + 1)
      - 7778:7778/udp
      # Query port used to list servers on the internet
      - 27015:27015/udp
      # RCON management port
      - 27020:27020/tcp
    environment:
      MAP: TheIsland
      CLUSTER: redactcluster
      EVENT: None
      MULTIHOME: 10.1.4.5
      OPTIONS: '-automanagedmods -NoTransferFromFiltering -ForceAllowCaveFlyers -usecache -NoBattleEye -crossplay -culture=en'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  ark-server:
